Added Forbidden as Error
amantinband/error-or pull request #73
Opened 2023-10-10 14:18 UTC by itsC-Ramesh

This PR introduces a new error type called "Forbidden" to the project. The "Forbidden" error type is useful when we must represent situations where an action or request is denied due to lack of permissions or authorization.

2023-10-10 14:20 UTC, itsC-Ramesh commented
#71

2024-02-11 23:03 UTC, OnikNoor97 requested changes

2024-02-11 23:03 UTC, OnikNoor97 commented on tests/ErrorTests.cs
> +    public void CreateError_WhenForbiddenError_ShouldHaveErrorTypeUnauthorized()
```suggestion
    public void CreateError_WhenForbiddenError_ShouldHaveErrorTypeForbidden()
```

2024-02-14 19:57 UTC, amantinband commented
Added via #86

2024-02-14 19:57 UTC, closed without merging